### ISSUE TITLE
Can you explain what is this appointment strategy?

### ISSUE THREAD

**Issue by devSarry** [timegridio/concierge#2]
Im looking through your code and it keeps popping up. Time slot is the default va
Is but what are some other examples that you could use. Also does changing the strategy have any effect ?

**Comment by alariva** [comment]
I thought of the booking strategies as follows:

`timeslot`: Specify a **date and a time** for reservation.
`dateslot`: Specify a just a **date** for reservation.

The strategies are different since the algorithms for searching for availability (referred as `Vacancy` model) have different behavior.

Still, this is under development and may change in the future.

You may join this [Gitter room](https://gitter.im/alariva/timegridDevelopment) for further discussion.
